country_codes = {
    8: "Albania",
    20: "Andorra",
    31: "Azerbaijan",
    32: "Argentina",
    36: "Australia",
    40: "Austria",
    50: "Bangladesh",
    51: "Armenia",
    68: "Bolivia",
    70: "Bosnia Herzegovina",
    76: "Brazil",
    100: "Bulgaria",
    104: "Myanmar",
    112: "Belarus",
    124: "Canada",
    152: "Chile",
    156: "China",
    158: "Taiwan ROC",
    170: "Colombia",
    191: "Croatia",
    196: "Cyprus",
    203: "Czechia",
    208: "Denmark",
    218: "Ecuador",
    231: "Ethiopia",
    233: "Estonia",
    246: "Finland",
    250: "France",
    268: "Georgia",
    276: "Germany",
    300: "Greece",
    320: "Guatemala",
    344: "Hong Kong SAR",
    348: "Hungary",
    352: "Iceland",
    360: "Indonesia",
    364: "Iran",
    368: "Iraq",
    380: "Italy",
    392: "Japan",
    398: "Kazakhstan",
    400: "Jordan",
    404: "Kenya",
    410: "South Korea",
    417: "Kyrgyzstan",
    428: "Latvia",
    422: "Lebanon",
    434: "Libya",
    440: "Lithuania",
    446: "Macao SAR",
    458: "Malaysia",
    462: "Maldives",
    484: "Mexico",
    496: "Mongolia",
    499: "Montenegro",
    504: "Morocco",
    528: "Netherlands",
    554: "New Zealand",
    558: "Nicaragua",
    566: "Nigeria",
    578: "Norway",
    586: "Pakistan",
    604: "Peru",
    608: "Philippines",
    616: "Poland",
    620: "Portugal",
    630: "Puerto Rico",
    642: "Romania",
    643: "Russia",
    688: "Serbia",
    702: "Singapore",
    703: "Slovakia",
    704: "Vietnam",
    705: "Slovenia",
    716: "Zimbabwe",
    724: "Spain",
    752: "Sweden",
    756: "Switzerland",
    762: "Tajikistan",
    764: "Thailand",
    788: "Tunisia",
    792: "Turkey",
    804: "Ukraine",
    807: "North Macedonia",
    818: "Egypt",
    826: "Great Britain",
    840: "United States",
    858: "Uruguay",
    862: "Venezuela",
    909: "Northern Ireland",
}

selected_variables = {
    # Technical Variables (ISO 3166-1 alpha-3 country code)
    'B_COUNTRY': 'country',
    # Social Values, Norms, Stereotypes (Q1-Q45)
    'Q1': 'importance_of_family',
    'Q2': 'importance_of_friends',
    'Q3': 'importance_of_leisure_time',
    'Q4': 'importance_of_politics',
    'Q5': 'importance_of_work',
    'Q6': 'importance_of_religion',
    'Q7': 'child_qualities_good_manners',
    'Q8': 'child_qualities_independence',
    'Q9': 'child_qualities_hard_work',
    'Q10': 'child_qualities_feeling_of_responsibility',
    'Q11': 'child_qualities_imagination',
    'Q12': 'child_qualities_tolerance_and_respect',
    'Q13': 'child_qualities_thrift_saving_money_and_things',
    'Q14': 'child_qualities_determination_perseverance',
    'Q15': 'child_qualities_religious_faith',
    'Q16': 'child_qualities_unselfishness',
    'Q17': 'child_qualities_obedience',
    'Q18': 'neighbors_drug_addicts',
    'Q19': 'neighbors_different_race',
    'Q20': 'neighbors_people_with_aids',
    'Q21': 'neighbors_immigrants_foreign_workers',
    'Q22': 'neighbors_homosexuals',
    'Q23': 'neighbors_different_religion',
    'Q24': 'neighbors_heavy_drinkers',
    'Q25': 'neighbors_unmarried_couples_living_together',
    'Q26': 'neighbors_different_language',
    'Q27': 'goal_make_parents_proud',
    'Q28': 'child_suffers_when_working_mother',
    'Q29': 'men_better_political_leaders_than_women',
    'Q30': 'university_more_important_for_boys',
    'Q31': 'men_better_business_executives_than_women',
    'Q32': 'being_a_housewife_just_as_fulfilling',
    'Q33': 'jobs_scarce_men_have_more_right_to_job_than_women',
    'Q34': 'jobs_scarce_employers_give_priority_to_nation_people',
    'Q35': 'problem_if_women_have_more_income_than_husband',
    'Q36': 'homosexual_couples_as_good_parents',
    'Q37': 'duty_towards_society_to_have_children',
    'Q38': 'children_duty_to_take_care_of_ill_parent',
    'Q39': 'people_who_dont_work_turn_lazy',
    'Q40': 'work_is_duty_towards_society',
    'Q41': 'work_always_comes_first_even_with_less_spare_time',
    'Q42': 'best_description_of_society',
    'Q43': 'future_changes_less_importance_on_work',
    'Q44': 'future_changes_more_emphasis_on_technology',
    'Q45': 'future_changes_greater_respect_for_authority',
    # Religious Values (Q164-Q175)
    'Q164': 'importance_of_god',
    'Q165': 'believe_in_god',
    'Q166': 'believe_in_life_after_death',
    'Q167': 'believe_in_hell',
    'Q168': 'believe_in_heaven',
    'Q169': 'whenever_science_and_religion_conflict_religion_is_right',
    'Q170': 'only_acceptable_religion_is_my_religion',
    'Q171': 'frequency_of_attending_religious_services',
    'Q172': 'frequency_of_praying',
    'Q173': 'religious_person',
    'Q174': 'meaning_of_religion_follow_religious_norms_and_ceremonies',
    'Q175': 'meaning_of_religion_make_sense_of_life_after_death',
    # Ethical Values (Q176-Q198)
    'Q176': 'trouble_choosing_moral_rules',
    'Q177': 'justifiable_claiming_government_benefits',
    'Q178': 'justifiable_avoiding_fare_on_public_transport',
    'Q179': 'justifiable_stealing_property',
    'Q180': 'justifiable_cheating_on_taxes',
    'Q181': 'justifiable_accepting_a_bribe_in_duties',
    'Q182': 'justifiable_homosexuality',
    'Q183': 'justifiable_prostitution',
    'Q184': 'justifiable_abortion',
    'Q185': 'justifiable_divorce',
    'Q186': 'justifiable_sex_before_marriage',
    'Q187': 'justifiable_suicide',
    'Q188': 'justifiable_euthanasia',
    'Q189': 'justifiable_man_beating_wife',
    'Q190': 'justifiable_parents_beating_children',
    'Q191': 'justifiable_violence_against_others',
    'Q192': 'justifiable_terrorism_as_political_ideological_or_religious_mean',
    'Q193': 'justifiable_having_casual_sex',
    'Q194': 'justifiable_political_violence',
    'Q195': 'justifiable_death_penalty',
    'Q196': 'government_right_keep_people_under_video_surveillance',
    'Q197': 'government_right_monitor_all_emails_and_internet_information',
    'Q198': 'government_right_collect_information_about_residents'
}